POST http://localhost:3030/api/skill
# Content Type precise what type of file you're sending (here json)
Content-Type: application/json

# Insert an empty line then insert the file to send
{
    "name": "JavaScript" 
}

# Triple # allows to separate requests (if you want many requests on the same file)

###
GET http://localhost:3030/api/skill

###
PUT http://localhost:3030/api/skill/4
Content-Type: application/json

{ 
    "name": "JS"
}

###
DELETE http://localhost:3030/api/skill/2