POST http://localhost:3030/api/wilder
# Content Type precise what type of file you're sending (here json)
Content-Type: application/json

# Insert an empty line then insert the file to send
{
    "name": "Thuy An",
    "city": "Schiltigheim"
}

# Triple # allows to separate requests (if you want many requests on the same file)

###
GET http://localhost:3030/api/wilder

###
PUT http://localhost:3030/api/wilder/1
Content-Type: application/json

{ 
    "name": "The Only And One True First Wilder !"
}

###
DELETE http://localhost:3030/api/wilder/20

###
PUT http://localhost:3030/api/wilder-add-skills
Content-Type: application/json

{
    "wilder": "Thuy An",
    "skill": ["HTML", "CSS"]
}

###
PUT http://localhost:3030/api/wilder-rate-skill
Content-Type: application/json

{
    "wilderId": 3,
    "skillId": 3,
    "rating": 7
}